# =============================================================================
# kaia-log-telegraf-kairos.conf
# Place in /etc/telegraf/telegraf.d/ on each Kairos CN node.
# =============================================================================

[[inputs.tail]]
  files = ["/var/kcnd/logs/kcnd.out"]
  from_beginning = false
  watch_method = "inotify"
  name_override = "kaia_log"
  data_format = "value"
  data_type = "string"

[[outputs.influxdb]]
  urls = ["http://node.kaia.io:45560"]
  database = "kairos_logs"
  namepass = ["kaia_log"]
